export const SUBMIT_ANSWER_TO_DB = 'SUBMIT_ANSWER_TO_DB';
export const CONTROL_TIMER = 'CONTROL_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const DECREMENT_TIMER = 'DECREMENT_TIMER';
export const FETCH_ANSWERS_FROM_DB = 'FETCH_ANSWERS_FROM_DB';