export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const START_TIMER = 'START_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const DECREMENT_TIMER = 'DECREMENT_TIMER';